import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { resolve } from 'path';
const envFile = readFileSync(resolve(process.cwd(), '.env.local'), 'utf-8');
envFile.split('\n').forEach(line => { const [k,...v] = line.split('='); if(k&&v.length) process.env[k.trim()] = v.join('=').trim(); });
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
function slugify(t){const m={'à':'a','á':'a','ả':'a','ã':'a','ạ':'a','ă':'a','ắ':'a','ằ':'a','ẳ':'a','ẵ':'a','ặ':'a','â':'a','ấ':'a','ầ':'a','ẩ':'a','ẫ':'a','ậ':'a','đ':'d','è':'e','é':'e','ẻ':'e','ẽ':'e','ẹ':'e','ê':'e','ế':'e','ề':'e','ể':'e','ễ':'e','ệ':'e','ì':'i','í':'i','ỉ':'i','ĩ':'i','ị':'i','ò':'o','ó':'o','ỏ':'o','õ':'o','ọ':'o','ô':'o','ố':'o','ồ':'o','ổ':'o','ỗ':'o','ộ':'o','ơ':'o','ớ':'o','ờ':'o','ở':'o','ỡ':'o','ợ':'o','ù':'u','ú':'u','ủ':'u','ũ':'u','ụ':'u','ư':'u','ứ':'u','ừ':'u','ử':'u','ữ':'u','ự':'u','ỳ':'y','ý':'y','ỷ':'y','ỹ':'y','ỵ':'y'};return t.toLowerCase().split('').map(c=>m[c]||c).join('').replace(/[^a-z0-9\s-]/g,'').replace(/[\s-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80);}
const IMGS=['https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80','https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80','https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80','https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&q=80','https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80','https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80','https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80','https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80','https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80','https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&q=80','https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80','https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80','https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80','https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80','https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80','https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&q=80','https://images.unsplash.com/photo-1526976668912-1a811878dd37?w=800&q=80','https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&q=80'];
const F=['Việc tổ chức sự kiện nội bộ ngày càng quan trọng với doanh nghiệp, giúp gắn kết và tạo động lực.','Doanh nghiệp tổ chức sự kiện thường xuyên giữ chân nhân viên hiệu quả hơn 30%.','Lên kế hoạch chi tiết từ ngân sách đến nhân sự là yếu tố quyết định thành công.','Sự Kiện Toàn Quốc luôn tối ưu ngân sách cho mọi quy mô doanh nghiệp.','MC chuyên nghiệp tạo sự khác biệt lớn cho sự kiện.','Đội ngũ kinh nghiệm hàng trăm sự kiện mỗi năm cam kết chất lượng.','Xu hướng 2026-2027: gamification, AI và trải nghiệm cá nhân hóa.','Menu ẩm thực đa dạng giúp sự kiện thêm trọn vẹn.','Liên hệ ngay để được tư vấn miễn phí và báo giá chi tiết.','Mạng lưới 63 tỉnh thành — tổ chức tại bất kỳ đâu trên toàn quốc.'];
function mc(title,excerpt){let h=`<p>${excerpt}</p>\n\n`;['Tổng Quan','Tại Sao?','Hướng Dẫn','Lưu Ý','Liên Hệ'].forEach(s=>{h+=`<h2>${s}</h2>\n`;for(let i=0;i<2;i++)h+=`<p>${F[Math.floor(Math.random()*F.length)]}</p>\n`;});h+=`<p><strong>Sự Kiện Toàn Quốc</strong> — <a href="tel:0854517868">0854 517 868</a></p>`;return h;}

const TITLES = [
// ===== T9: Workshop & Đào tạo (30 ngày = 90 bài) =====
'Hướng Dẫn Tổ Chức Workshop Leadership Cho Quản Lý Cấp Trung',
'Top 10 Chủ Đề Workshop Kỹ Năng Mềm Hot Nhất Cho Doanh Nghiệp 2026',
'Cách Tổ Chức Design Thinking Workshop Cho Team Sáng Tạo',
'Workshop Communication Skills: Nâng Cao Giao Tiếp Nội Bộ',
'Hướng Dẫn Tổ Chức Workshop Time Management Cho Nhân Viên',
'Tổ Chức Buổi Chia Sẻ Kiến Thức Knowledge Sharing Nội Bộ',
'Workshop Presentation Skills: Cách Thuyết Trình Ấn Tượng',
'Hướng Dẫn Tổ Chức Mentoring Day Kết Nối Mentor-Mentee',
'Cách Tổ Chức Career Day Nội Bộ Giúp Nhân Viên Phát Triển',
'Workshop Problem Solving: Kỹ Năng Giải Quyết Vấn Đề Cho Team',
'Hướng Dẫn Tổ Chức Hội Nghị Khách Hàng Annual Customer Meeting',
'Cách Setup Hội Thảo Chuyên Đề Seminar Cho 100-300 Người',
'Tổ Chức Lễ Ra Mắt Sản Phẩm Product Launch Event Chuyên Nghiệp',
'Hướng Dẫn Tổ Chức Họp Báo Press Conference Cho Doanh Nghiệp',
'Kịch Bản Lễ Khai Trương Chi Nhánh Mới Ấn Tượng Và Chuyên Nghiệp',
'Cách Tổ Chức Grand Opening Cửa Hàng Thu Hút Khách Hàng',
'Hướng Dẫn Tổ Chức Lễ Ký Kết Hợp Tác MOU Signing Ceremony',
'Tổ Chức Hội Nghị Tổng Kết Annual Meeting Cho Tập Đoàn Lớn',
'Cách Setup Conference Room Chuyên Nghiệp Cho Hội Thảo 200 Người',
'Hướng Dẫn Tổ Chức Panel Discussion Chuyên Gia Cho Sự Kiện',
'Workshop Teamwork: 15 Bài Tập Xây Dựng Đội Nhóm Hiệu Quả',
'Cách Tổ Chức Ngày Hội Tuyển Dụng Job Fair Tại Công Ty',
'Hướng Dẫn Tổ Chức Training Bootcamp 3 Ngày Cho Nhân Viên Mới',
'Workshop Sales Skills: Kỹ Năng Bán Hàng Cho Đội Kinh Doanh',
'Cách Tổ Chức Demo Day Cho Startup Nội Bộ Và Innovation Lab',
'Hướng Dẫn Tổ Chức Award Ceremony Trao Giải Sáng Kiến Quý 3',
'Kịch Bản Lễ Tổng Kết Quý 3 Chuyên Nghiệp Cho Doanh Nghiệp',
'Cách Viết Báo Cáo Tổng Kết Q3 Thu Hút Và Trực Quan',
'Template Slide Tổng Kết Q3 Đẹp Cho Manager Download Free',
'Teambuilding Mùa Thu 2026: 10 Ý Tưởng Hoạt Động Ngoài Trời',
'Hướng Dẫn Tổ Chức Trung Thu Công Ty Cho Con Nhân Viên',
'Cách Tổ Chức Đêm Hội Trung Thu Tại Công Ty Ấn Tượng',
'Ý Tưởng Quà Trung Thu Cho Nhân Viên Và Đối Tác 2026',
'Teambuilding Mùa Thu Đà Lạt: Hoa Dã Quỳ Và Hoạt Động Outdoor',
'Company Trip Mùa Thu Sapa: Ruộng Bậc Thang Vàng Óng',
'Hướng Dẫn Lên Budget Year End Party 2026 Cho HR Chi Tiết',
'Chuẩn Bị Year End Party Từ Tháng 10: Checklist Complete Cho HR',
'Top 20 Venue Year End Party Đà Nẵng Sang Trọng 2026',
'Báo Giá Gói Year End Party Trọn Gói Tại TPHCM 2026',
'Hướng Dẫn Chọn Theme Year End Party Phù Hợp Văn Hóa Công Ty',
'Cách Tổ Chức Cuộc Thi Halloween Costume Tại Công Ty',
'Hướng Dẫn Trang Trí Văn Phòng Halloween Cho Sự Kiện Nội Bộ',
'Teambuilding Halloween: 10 Trò Chơi Kinh Dị Vui Nhộn Cho Đội Nhóm',
'Kịch Bản MC Đêm Halloween Party Tại Công Ty Chi Tiết',
'Ý Tưởng Menu Tiệc Halloween Cho Sự Kiện Nội Bộ Sáng Tạo',
'Tổ Chức Escape Room Halloween Theme Cho Team Building',
'Hướng Dẫn Tổ Chức Movie Night Halloween Cho Nhân Viên',
'Cách Tổ Chức Cuộc Thi Bí Ngô Carving Cho Team Sáng Tạo',
'Workshop Digital Marketing Cho Doanh Nghiệp Nhỏ Và Vừa',
'Hướng Dẫn Tổ Chức Wellness Day: Yoga Và Meditation Tại Văn Phòng',
'Cách Tổ Chức Ngày Hội Sức Khỏe Health Fair Cho Nhân Viên',
'Teambuilding Cooking Class Ẩm Thực Mùa Thu Cho Đội Nhóm',
'Hướng Dẫn Tổ Chức Book Club Nội Bộ Tăng Văn Hóa Đọc',
'Workshop Stress Management: Quản Lý Áp Lực Công Việc Cuối Năm',
'Cách Tổ Chức Cuộc Thi Viết Blog Nội Bộ Cho Nhân Viên',
'Hướng Dẫn Tổ Chức Volunteer Day Cuối Năm Cho Doanh Nghiệp',
'Teambuilding Mùa Thu Núi Bà Đen: Leo Núi Và Gắn Kết',
'Company Trip Mùa Thu Ninh Bình: Tràng An Mùa Lúa Vàng',
'Hướng Dẫn Tổ Chức Sự Kiện 20/10 Cho Nữ Nhân Viên',
'Kịch Bản Ngày Phụ Nữ Việt Nam 20/10 Tại Công Ty Ấn Tượng',
// ===== T11-T12: Year End Party cao điểm (61 ngày = 183 bài) =====
'Year End Party 2026: 30 Concept Độc Đáo Từ Sang Trọng Đến Tiết Kiệm',
'Kịch Bản Year End Party 2026 Chi Tiết Từng Phút Cho MC',
'Hướng Dẫn Tổ Chức Year End Party Công Ty Dưới 100 Người',
'Year End Party Cho Công Ty Lớn 500+ Người: Hướng Dẫn A-Z',
'Top 15 Ca Sĩ Cho Thuê Year End Party 2026 Giá Từ 5 Triệu',
'Cách Tổ Chức Year End Party Online Cho Team Remote',
'Hướng Dẫn Trang Trí Year End Party Theme Hollywood Glamour',
'Year End Party Theme Tropical Paradise: Setup Và Trang Trí',
'Kịch Bản Trò Chơi Hay Nhất Cho Year End Party 2026',
'Hướng Dẫn Tổ Chức Lucky Draw Rút Thăm May Mắn YEP Hấp Dẫn',
'Top 20 Quà Tặng Lucky Draw Year End Party Được Yêu Thích Nhất',
'Cách Tổ Chức Cuộc Thi Nhảy Dance Battle Tại Year End Party',
'Hướng Dẫn Setup Âm Thanh Ánh Sáng Cho Year End Party 200 Người',
'Year End Party Theme Gatsby: Concept Cổ Điển Sang Trọng',
'Cách Tổ Chức Year End Party Ngoài Trời Garden Party Style',
'Hướng Dẫn Làm Slideshow Kỷ Niệm Một Năm Cho Year End Party',
'Kịch Bản Vinh Danh Top Performer Tại Year End Party Cảm Động',
'Cách Tổ Chức Year End Party Cho Startup Ngân Sách Dưới 20 Triệu',
'Menu Tiệc Year End Party: Buffet Cocktail Hay Set Menu?',
'Hướng Dẫn Dress Code Year End Party Cho Nhân Viên',
'Tiệc Tất Niên 2026: Kịch Bản Và Ý Tưởng Cho Mọi Quy Mô',
'Cách Tổ Chức Tiệc Tất Niên Phòng Ban Ấm Cúng Dưới 10 Triệu',
'Gala Dinner 2026: Hướng Dẫn Tổ Chức Từ A-Z Cho Doanh Nghiệp',
'Gala Dinner Theme Awards Night: Kịch Bản Đêm Trao Giải',
'Hướng Dẫn Tổ Chức Lễ Vinh Danh Nhân Viên Xuất Sắc Năm 2026',
'Top 10 Hạng Mục Giải Thưởng Cuối Năm Sáng Tạo Cho Doanh Nghiệp',
'Cách Làm Video Tribute Cho Nhân Viên Nghỉ Hưu Hoặc Chuyển Công Tác',
'Kịch Bản Lễ Tổng Kết Cuối Năm 2026 Cho Doanh Nghiệp Vừa Và Nhỏ',
'Hướng Dẫn Tổ Chức Lễ Tổng Kết Năm Cho Tập Đoàn 1000+ Người',
'Template Báo Cáo Tổng Kết Năm 2026 Cho CEO Và Ban Lãnh Đạo',
'Year End Party Theme Neon Glow: Concept Sáng Tạo Cho Giới Trẻ',
'Cách Tổ Chức Pre-YEP Teambuilding Gắn Kết Trước Tiệc Cuối Năm',
'Hướng Dẫn Tổ Chức Secret Santa Tặng Quà Bí Mật Tại Văn Phòng',
'Tổ Chức Lễ Giáng Sinh Christmas Party Tại Công Ty Vui Nhộn',
'Cách Trang Trí Văn Phòng Giáng Sinh Đẹp Với Chi Phí Dưới 3 Triệu',
'Kịch Bản MC Tiệc Giáng Sinh Tại Công Ty Vui Và Ấm Áp',
'Year End Party Theme Winter Wonderland: Setup Mùa Đông Cổ Tích',
'Hướng Dẫn Tổ Chức Countdown Party Đón Năm Mới 2027 Tại Công Ty',
'Cách Tổ Chức Tiệc Chia Tay Năm Cũ 2026 Đáng Nhớ Cho Team',
'Tổng Kết Các Xu Hướng Sự Kiện Doanh Nghiệp 2026 Và Dự Báo 2027',
// ===== T1/2027: Kickoff & đầu năm =====
'Kịch Bản Lễ Kickoff Đầu Năm 2027 Truyền Cảm Hứng Cho Toàn Công Ty',
'Hướng Dẫn Tổ Chức Họp Mặt Đầu Xuân Tân Niên 2027',
'Cách Tổ Chức Tiệc Tân Niên 2027 Cho Doanh Nghiệp Vừa Và Nhỏ',
'Teambuilding Đầu Năm 2027: 15 Hoạt Động Khởi Động Năng Lượng Mới',
'Hướng Dẫn Tổ Chức Team Reconnect Sau Kỳ Nghỉ Tết 2027',
'Workshop Goal Setting 2027: Xây Dựng Mục Tiêu Năm Mới Cho Team',
'Cách Tổ Chức Vision Board Workshop Cho Nhân Viên Đầu Năm',
'Hướng Dẫn Tổ Chức Company Trip Xuân 2027 Kết Hợp Teambuilding',
'Teambuilding Xuân 2027: Khám Phá Đường Hoa Và Hoạt Động Văn Hóa',
'Top 10 Địa Điểm Company Trip Xuân 2027 Gần TPHCM Và Hà Nội',
'Cách Tổ Chức Lì Xì Đầu Năm Cho Nhân Viên Ý Nghĩa Và Vui Vẻ',
'Hướng Dẫn Tổ Chức Buổi Tea Break Đầu Xuân Tại Văn Phòng',
'Teambuilding Cho Nhân Viên Mới Tuyển Dụng Đầu Năm 2027',
'Workshop New Year Resolution: Cam Kết Cá Nhân Và Đội Nhóm 2027',
'Cách Xây Dựng Văn Hóa Công Ty Qua Hoạt Động Team Building Q1/2027',
'Hướng Dẫn Tổ Chức OKR Meeting Q1 Hiệu Quả Cho Toàn Công Ty',
'Teambuilding Valentine 14/2: Hoạt Động Gắn Kết Đôi Và Đội Nhóm',
'Cách Tổ Chức Ngày Valentine Tại Công Ty Lãng Mạn Và Vui Nhộn',
'Hướng Dẫn Tổ Chức Women Day 8/3 Tại Công Ty Ý Nghĩa 2027',
'Kịch Bản Ngày Quốc Tế Phụ Nữ 8/3 Cho Các Chị Em Công Sở',
'Teambuilding Kết Hợp Từ Thiện Đầu Năm: Trao Yêu Thương 2027',
'Hướng Dẫn Tổ Chức Sinh Hoạt Đoàn Thể 26/3 Cho Công Ty',
'Cách Tổ Chức Lễ Kỷ Niệm Ngày Thành Lập Đoàn 26/3 Tại DN',
'Teambuilding Trồng Cây Xanh Đầu Xuân: Hoạt Động CSR 2027',
'Hướng Dẫn Tổ Chức Mini Marathon Nội Bộ Đầu Năm 2027',
'Company Trip Tết Hàn Thực 3/3: Làm Bánh Trôi Và Gắn Kết Team',
'Workshop Creative Thinking: Tư Duy Sáng Tạo Cho Doanh Nghiệp 2027',
'Cách Tổ Chức Ngày Hội Sáng Tạo Innovation Fair Nội Bộ 2027',
'Hướng Dẫn Tổ Chức Tổng Kết Q1/2027 Hiệu Quả Và Truyền Cảm Hứng',
'Kịch Bản Tổng Kết Quý 1/2027: Template Và Hướng Dẫn MC',
// ===== T3-T4/2027: Chuẩn bị mùa hè mới =====
'Teambuilding Mùa Xuân 2027: 20 Ý Tưởng Hoạt Động Ngoài Trời',
'Hướng Dẫn Lên Kế Hoạch Teambuilding Hè 2027 Từ Tháng 3',
'Top 10 Xu Hướng Teambuilding Mới Nhất 2027 Cho Doanh Nghiệp',
'Company Trip Hè 2027: So Sánh Các Điểm Đến Hot Nhất',
'Cách Tổ Chức Team Building Cho Gen Z: Hoạt Động Phù Hợp 2027',
'Hướng Dẫn Tổ Chức Giỗ Tổ Hùng Vương 10/3 Tại Công Ty',
'Teambuilding 30/4 - 1/5 2027: Kế Hoạch Cho Kỳ Nghỉ Dài',
'Cách Tổ Chức Pre-Summer Party Chào Hè 2027 Tại Văn Phòng',
'Hướng Dẫn Đặt Tour Company Trip Hè 2027 Sớm Giá Tốt',
'Top 15 Điểm Đến Teambuilding Biển Mới Nổi 2027',
'Teambuilding Phú Quốc 2027: Cập Nhật Địa Điểm Và Hoạt Động Mới',
'Company Trip Đà Nẵng 2027: Những Thay Đổi Và Điểm Mới',
'Hướng Dẫn Tổ Chức Company Trip Nước Ngoài Bangkok Cho Công Ty VN',
'Teambuilding Singapore: Company Trip Nước Ngoài Gần Cho DN Việt',
'Cách Tổ Chức Team Building Kết Hợp Du Lịch Bali Cho Doanh Nghiệp',
'Hướng Dẫn Tổ Chức Sports Day Mùa Hè 2027 Cho Doanh Nghiệp',
'Teambuilding Adventure 2027: Zipline Và Canyoning Mới Tại VN',
'Cách Tổ Chức Cuộc Thi Sáng Kiến Mùa Hè Summer Innovation 2027',
'Hướng Dẫn Tổ Chức Ngày Hội STEM Cho Doanh Nghiệp Công Nghệ 2027',
'Teambuilding Cho Remote Team 2027: Hoạt Động Hybrid Sáng Tạo',
'Cách Tổ Chức Company Trip Camping Glamping Cho 50-100 Người',
'Hướng Dẫn Tổ Chức Cuộc Thi Video TikTok Nội Bộ Cho Nhân Viên',
'Teambuilding Earth Day 22/4: Hoạt Động Xanh Cho Doanh Nghiệp',
'Cách Tổ Chức Lễ 30/4 - 1/5 Tại Công Ty: Kịch Bản 2027',
'Hướng Dẫn Tổ Chức Summer Kickoff Party Chào Hè 2027',
'Teambuilding Và AI 2027: Ứng Dụng Công Nghệ Vào Team Building',
'Cách Tổ Chức Hackathon AI Nội Bộ Cho Doanh Nghiệp 2027',
'Hướng Dẫn Tổ Chức Ngày Hội Văn Hóa Đa Sắc Cho Công Ty Đa Quốc Gia',
'Kế Hoạch Sự Kiện Nội Bộ Hè 2027: Template Cho HR',
'Tổng Kết Content Plan T4/2027: Đánh Giá Và Hướng Đi Tiếp Theo',
];

const CATS=['teambuilding','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','su-kien-noi-bo','tong-ket','tong-ket','tong-ket','tong-ket','teambuilding','company-trip','company-trip','teambuilding','teambuilding','company-trip'];
const HOURS=[7,12,19];

console.log(`🚀 Tạo bài T9/2026 → T4/2027 (${TITLES.length} bài)\n`);
let ok=0, fail=0;
const start = new Date('2026-09-01T00:00:00+07:00');

for (let i = 0; i < TITLES.length; i++) {
  const title = TITLES[i], day = Math.floor(i/3), hour = HOURS[i%3];
  const d = new Date(start); d.setDate(d.getDate()+day); d.setHours(hour,0,0,0);
  const excerpt = title.replace(/:/g,' —')+'. Hướng dẫn chi tiết từ Sự Kiện Toàn Quốc.';
  const cat = CATS[i%CATS.length]||'teambuilding';
  const {error} = await supabase.from('posts').insert([{title,slug:slugify(title),excerpt,content:mc(title,excerpt),featured_image:IMGS[i%IMGS.length],category_id:cat,tags:['Sự kiện','Doanh nghiệp','2026-2027'],is_published:false,published_at:d.toISOString(),meta_title:title,meta_description:excerpt.slice(0,160)}]);
  if(error){if(error.message?.includes('duplicate')||error.code==='23505')console.log(`⏭️  Skip: ${title.slice(0,50)}`);else{console.error(`❌ ${title.slice(0,40)} → ${error.message}`);fail++;}}
  else{console.log(`✅ [${d.toLocaleDateString('vi-VN')} ${hour}:00] ${title.slice(0,55)}`);ok++;}
}
console.log(`\n📊 T9/26→T4/27: ${ok} thành công, ${fail} lỗi`);
